#!/bin/sh

rm -rf build
mkdir -p build/bin
mkdir build/lib
tag=$(uname -r | tr -d '.')
libs=$(ldd gdl | awk '/\.so/{print $7}')
install=build/bin/install_gdl
echo "#!/bin/sh" >$install
for lib in $libs ; do
    cp $lib build/lib
    printf "mkdir -p %s\n" $(dirname $lib) >>$install
    printf "[ -L %s ] || ln -s /usr/local/lib/%s %s\n" $lib $(basename $lib) $lib >>$install
done
cp gdl build/bin
tar zcf gdl${tag}.tgz -C build lib bin
rm -rf build
